[package]
name = "mkk_basis"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.24.0", features = ["v4", "serde"] }
chrono = { version = "0.4.45", features = ["serde"] }
sqlx = { version = "0.9.0", features = ["postgres", "chrono", "runtime-tokio", "macros", "uuid"] }
serde = { version = "1.0.228", features = ["derive"] }
config = "0.15.25"
tokio = { version = "1.52.3", features = ["full"] }
clap = { version = "4.6.1", features = ["derive"] }
log = "0.4.33"
axum = "0.8.9"
serde_json = "1.0.151"
env_logger = "0.11.11"
fake = { version = "5.1.0", features = ["derive", "chrono", "uuid"] }
reqwest = { version = "0.13.4", features = ["form", "json"] }
tower-http = { version = "0.7.0", features = ["fs"] }
argon2 = { version = "0.5.3", features = ["std"] }
regex = "1.13.1"
once_cell = "1.21.4"
email_address = "0.2.9"
http = "1.5.0"
